name: remote-gpu-exp

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check GPU
        run: |
          which conda

      # - name: Setup conda env
      #   shell: bash -l {0}
      #   run: |
      #     conda create -n recursivemas python=3.10 -y


